ALTER TABLE public.groups 
ADD COLUMN IF NOT EXISTS closing_day INTEGER DEFAULT 1 CHECK (closing_day BETWEEN 1 AND 31),
ADD COLUMN IF NOT EXISTS due_day INTEGER DEFAULT 10 CHECK (due_day BETWEEN 1 AND 31);